source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bcrypt-ruby'
gem 'figaro'

group :production do
  gem 'rails_12factor'
  gem 'thin'
end

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'minitest-rails'
  gem 'pry'
end

group :development do
  gem 'guard-minitest'
end
group :test do
  gem 'webmock', "~> 1.8.0"
  gem "vcr", "~> 2.8.0"
  gem 'mocha'
  gem 'simplecov'
end
