source 'https://rubygems.org'

gem 'rails', '4.0.2'

gem 'pg'
gem "koala", "~> 1.8.0rc1"
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem "minitest-rails"
gem 'pry'
gem 'figaro'
gem 'bcrypt-ruby'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'mocha'
end

group :production do
  gem 'rails_12factor'
  gem 'thin'
end

group :test do
  gem "vcr", "~> 2.8.0"
  gem "minitest-rails-capybara"
  gem 'webmock', "~> 1.8.0"
  gem 'simplecov', :require => false
end
