source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem "koala", "~> 1.8.0rc1"
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem "minitest-rails"
gem 'pry'

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem "vcr", "~> 2.8.0"
  gem 'webmock', "~> 1.8.0"
end


group :test do
  gem "minitest-rails-capybara"
end
