# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

  APP_CONFIRMATION: "$2a$10$MBqCBiZe4Z6KAgAvGssevOEm45HbyLNVxKi2ai92YAAWqVGuUSRAq"
  AUTH_ID: "$2a$10$8NE5e2jvKu.NOMgP45Zd1uqoFKXKPtbacP4soIyDUNbxoFXruKwxu"
  APP_SECRET: "$2a$10$lsG2ZnFYo1d4KSeELGzu.eBce5N./SteNPPW3.mMgcxbBLI94o3Fi"
